id integer NOT NULL DEFAULT nextval('plants_id_seq'::regclass),
common_name text COLLATE pg_catalog."default" NOT NULL,
scientific_name text COLLATE pg_catalog."default" NOT NULL,
sunlight_care text COLLATE pg_catalog."default",
water_care text COLLATE pg_catalog."default",
temperature_care text COLLATE pg_catalog."default",
humidity_care text COLLATE pg_catalog."default",
growing_tips text COLLATE pg_catalog."default",
propagation_tips text COLLATE pg_catalog."default",
common_pests text COLLATE pg_catalog."default",
image_url text COLLATE pg_catalog."default",
family text COLLATE pg_catalog."default",
genus text COLLATE pg_catalog."default",
year integer,
edible boolean,
edible_part text COLLATE pg_catalog."default",
edible_notes text COLLATE pg_catalog."default",
medicinal boolean,
medicinal_notes text COLLATE pg_catalog."default",
toxicity text COLLATE pg_catalog."default",
synonyms text COLLATE pg_catalog."default",
native_status text COLLATE pg_catalog."default",
conservation_status text COLLATE pg_catalog."default",
"timestamp" timestamp without time zone DEFAULT now(),
