"""empty message

Revision ID: 1e3517bfe104
Revises: 
Create Date: 2023-05-18 09:16:09.750488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e3517bfe104'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('scientific_name', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('other_name', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('origin', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('dimension', sa.String(length=255), nullable=True),
    sa.Column('cycle', sa.String(length=255), nullable=True),
    sa.Column('attracts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('propagation', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('hardiness', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('hardiness_location', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('watering', sa.String(length=255), nullable=True),
    sa.Column('sunlight', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('maintenance', sa.String(length=255), nullable=True),
    sa.Column('care_guides', sa.String(length=255), nullable=True),
    sa.Column('soil', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('growth_rate', sa.String(length=255), nullable=True),
    sa.Column('drought_tolerant', sa.Boolean(), nullable=True),
    sa.Column('salt_tolerant', sa.Boolean(), nullable=True),
    sa.Column('thorny', sa.Boolean(), nullable=True),
    sa.Column('invasive', sa.Boolean(), nullable=True),
    sa.Column('tropical', sa.Boolean(), nullable=True),
    sa.Column('indoor', sa.Boolean(), nullable=True),
    sa.Column('care_level', sa.String(length=255), nullable=True),
    sa.Column('pest_susceptibility', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pest_susceptibility_api', sa.String(length=255), nullable=True),
    sa.Column('flowers', sa.Boolean(), nullable=True),
    sa.Column('flowering_season', sa.String(length=255), nullable=True),
    sa.Column('flower_color', sa.String(length=255), nullable=True),
    sa.Column('cones', sa.Boolean(), nullable=True),
    sa.Column('fruits', sa.Boolean(), nullable=True),
    sa.Column('edible_fruit', sa.Boolean(), nullable=True),
    sa.Column('edible_fruit_taste_profile', sa.String(length=255), nullable=True),
    sa.Column('fruit_nutritional_value', sa.String(length=255), nullable=True),
    sa.Column('fruit_color', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('harvest_season', sa.String(length=255), nullable=True),
    sa.Column('harvest_method', sa.String(length=255), nullable=True),
    sa.Column('leaf', sa.Boolean(), nullable=True),
    sa.Column('leaf_color', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('edible_leaf', sa.Boolean(), nullable=True),
    sa.Column('edible_leaf_taste_profile', sa.String(length=255), nullable=True),
    sa.Column('leaf_nutritional_value', sa.String(length=255), nullable=True),
    sa.Column('cuisine', sa.Boolean(), nullable=True),
    sa.Column('cuisine_list', sa.String(length=255), nullable=True),
    sa.Column('medicinal', sa.Boolean(), nullable=True),
    sa.Column('medicinal_use', sa.String(length=255), nullable=True),
    sa.Column('medicinal_method', sa.String(length=255), nullable=True),
    sa.Column('poisonous_to_humans', sa.Integer(), nullable=True),
    sa.Column('poison_effects_to_humans', sa.String(length=255), nullable=True),
    sa.Column('poison_to_humans_cure', sa.String(length=255), nullable=True),
    sa.Column('poisonous_to_pets', sa.Integer(), nullable=True),
    sa.Column('poison_effects_to_pets', sa.String(length=255), nullable=True),
    sa.Column('poison_to_pets_cure', sa.String(length=255), nullable=True),
    sa.Column('rare', sa.String(length=255), nullable=True),
    sa.Column('rare_level', sa.String(length=255), nullable=True),
    sa.Column('endangered', sa.String(length=255), nullable=True),
    sa.Column('endangered_level', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('problem', sa.String(length=255), nullable=True),
    sa.Column('default_image', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
